In [1]:
import requests
import json
import urllib
import matplotlib.pyplot as plt
import numpy as np
from pandas import DataFrame as pd

In [225]:
ip = "127.0.0.1"
port = "5002"
query = "http://{}:{}/health".format(ip, port)
r = requests.get(query)
json.loads(r.text)

{'success': True}

In [226]:
query = "http://{}:{}/getDistinct".format(ip, port)
r = requests.get(query)
inp = json.loads(r.text)
dist = pd.from_dict(inp)
dist

    symbol
0     MSFT
1      SPX
10     AMD
100    CNC
101    CNP
102    CTL
103   CERN
104     CF
105   SCHW
106   CHTR
107    CVX
108    CMG
109     CB
11     AAP
110    CHD
111     CI
112    XEC
113   CINF
114   CTAS
115   CSCO
116      C
117    CFG
118   CTXS
119    CLX
12     AES
120    CME
121    CMS
122     KO
123   CTSH
124     CL
..     ...
72   BRK.B
73     BBY
74    BIIB
75     BLK
76     HRB
77      BA
78    BKNG
79     BWA
8     ATVI
80     BXP
81     BSX
82     BHF
83     BMY
84    AVGO
85      BR
86    CHRW
87     COG
88    CDNS
89     CPB
9     ADBE
90     COF
91     CAH
92     KMX
93     CCL
94     CAT
95    CBOE
96    CBRE
97     CBS
98      CE
99    CELG

[501 rows x 1 columns]

In [227]:
query = "http://{}:{}/getStock/MSFT".format(ip, port)
r = requests.get(query)
inp = json.loads(r.text)
df = pd.from_dict(inp)
df = df.sort_values(by='date')
df

,adjusted_close,close,date,dividend_amount,high,id,low,open,split_coefficient,symbol,volume
5415,10.6408,131.13,1998-01-02,0.0,131.500,MSFT1998-01-02,129.5000,129.63,1.0,MSFT,4968500
5414,10.5799,130.38,1998-01-05,0.0,133.630,MSFT1998-01-05,127.8700,131.25,1.0,MSFT,10047200
5413,10.6408,131.13,1998-01-06,0.0,133.000,MSFT1998-01-06,129.2500,129.75,1.0,MSFT,8479300
5412,10.5134,129.56,1998-01-07,0.0,131.190,MSFT1998-01-07,127.5000,129.88,1.0,MSFT,7686600
5411,10.5897,130.50,1998-01-08,0.0,132.130,MSFT1998-01-08,127.5000,128.63,1.0,MSFT,9702400
5410,10.3057,127.00,1998-01-09,0.0,131.500,MSFT1998-01-09,125.8700,130.06,1.0,MSFT,10941800
5409,10.5085,129.50,1998-01-12,0.0,130.000,MSFT1998-01-12,124.3700,124.62,1.0,MSFT,9799200
5408,10.7220,132.13,1998-01-13,0.0,132.250,MSFT1998-01-13,128.1300,129.50,1.0,MSFT,8368200
5407,10.6408,131.13,1998-01-14,0.0,132.500,MSFT1998-01-14,129.2500,132.13,1.0,MSFT,6846800
5406,10.7366,132.31,1998-01-15,0.0,133.000,MSFT1998-01-15,129.8800,130.38,1.0,MSFT,6327800
5405,10.9751,135.25,1998-01-16,0.0,135.380,MSFT1998-01-16,132.3100,132.38,1.0,MSFT,9117900
5404,11.1829,137.81,1998-01-20,0.0,138.000,MSFT1998-01-20,134.0000,134.13,1.0,MSFT,8119500
5403,11.1171,137.00,1998-01-21,0.0,138.440,MSFT1998-01-21,135.6300,137.25,1.0,MSFT,10695900
5402,11.2494,138.63,1998-01-22,0.0,139.880,MSFT1998-01-22,135.3100,135.56,1.0,MSFT,19892400
5401,11.2186,138.25,1998-01-23,0.0,139.440,MSFT1998-01-23,136.7000,138.75,1.0,MSFT,7914000
5400,11.5026,141.75,1998-01-26,0.0,141.880,MSFT1998-01-26,138.4500,139.88,1.0,MSFT,9284700
5399,11.7817,145.19,1998-01-27,0.0,145.880,MSFT1998-01-27,141.5600,142.38,1.0,MSFT,12192600
5398,12.0909,149.00,1998-01-28,0.0,149.500,MSFT1998-01-28,145.5000,146.25,1.0,MSFT,9923400
5397,12.0300,148.25,1998-01-29,0.0,150.130,MSFT1998-01-29,147.5000,148.94,1.0,MSFT,9196400
5396,12.1063,149.19,1998-01-30,0.0,150.000,MSFT1998-01-30,147.6300,148.63,1.0,MSFT,6258900
5395,12.5680,154.88,1998-02-02,0.0,155.130,MSFT1998-02-02,150.5000,151.75,1.0,MSFT,12299700
5394,12.6492,155.88,1998-02-03,0.0,156.130,MSFT1998-02-03,153.8100,155.13,1.0,MSFT,7671800
5393,12.7247,156.81,1998-02-04,0.0,158.000,MSFT1998-02-04,155.0600,155.88,1.0,MSFT,7742600
5392,12.6135,155.44,1998-02-05,0.0,158.750,MSFT1998-02-05,154.7500,158.13,1.0,MSFT,8376800
5391,12.8318,158.13,1998-02-06,0.0,158.250,MSFT1998-02-06,155.1300,155.38,1.0,MSFT,6258800
5390,12.7555,157.19,1998-02-09,0.0,158.880,MSFT1998-02-09,155.6300,158.75,1.0,MSFT,6835200
5389,12.9227,159.25,1998-02-10,0.0,159.500,MSFT1998-02-10,156.7500,157.25,1.0,MSFT,6012400
5388,12.8975,158.94,1998-02-11,0.0,160.060,MSFT1998-02-11,157.0600,159.38,1.0,MSFT,9557500
5387,12.8821,158.75,1998-02-12,0.0,158.940,MSFT1998-02-12,156.4400,158.06,1.0,MSFT,9582300
5386,12.7807,157.50,1998-02-13,0.0,158.750,MSFT1998-02-13,157.3800,158.63,1.0,MSFT,5275400
...,...,...,...,...,...,...,...,...,...,...,...
29,123.6800,123.68,2019-05-31,0.0,124.615,MSFT2019-05-31,123.3200,124.23,1.0,MSFT,26646769
28,119.8400,119.84,2019-06-03,0.0,124.370,MSFT2019-06-03,119.0100,123.85,1.0,MSFT,37983637
27,123.1600,123.16,2019-06-04,0.0,123.280,MSFT2019-06-04,120.6522,121.28,1.0,MSFT,29382642
26,125.8300,125.83,2019-06-05,0.0,125.870,MSFT2019-06-05,124.2100,124.95,1.0,MSFT,24926140
25,127.8200,127.82,2019-06-06,0.0,127.970,MSFT2019-06-06,125.6000,126.44,1.0,MSFT,21458961
24,131.4000,131.40,2019-06-07,0.0,132.250,MSFT2019-06-07,128.2600,129.19,1.0,MSFT,33885588
23,132.6000,132.60,2019-06-10,0.0,134.080,MSFT2019-06-10,132.0000,132.40,1.0,MSFT,26477098
22,132.1000,132.10,2019-06-11,0.0,134.240,MSFT2019-06-11,131.2757,133.88,1.0,MSFT,23913731
21,131.4900,131.49,2019-06-12,0.0,131.970,MSFT2019-06-12,130.7100,131.40,1.0,MSFT,17092464
20,132.3200,132.32,2019-06-13,0.0,132.670,MSFT2019-06-13,131.5600,131.98,1.0,MSFT,17200848
19,132.4500,132.45,2019-06-14,0.0,133.790,MSFT2019-06-14,131.6400,132.26,1.0,MSFT,17821703
18,132.8500,132.85,2019-06-17,0.0,133.730,MSFT2019-06-17,132.5300,132.63,1.0,MSFT,14517785
17,135.1600,135.16,2019-06-18,0.0,135.240,MSFT2019-06-18,133.5700,134.19,1.0,MSFT,25934458
16,135.6900,135.69,2019-06-19,0.0,135.930,MSFT2019-06-19,133.8100,135.00,1.0,MSFT,23744441
15,136.9500,136.95,2019-06-20,0.0,137.660,MSFT2019-06-20,135.7200,137.45,1.0,MSFT,33042592
14,136.9700,136.97,2019-06-21,0.0,137.730,MSFT2019-06-21,136.4600,136.58,1.0,MSFT,36727892
13,137.7800,137.78,2019-06-24,0.0,138.400,MSFT2019-06-24,137.0000,137.00,1.0,MSFT,20628841
12,133.4300,133.43,2019-06-25,0.0,137.590,MSFT2019-06-25,132.7300,137.25,1.0,MSFT,33327420
11,133.9300,133.93,2019-06-26,0.0,135.740,MSFT2019-06-26,133.6000,134.35,1.0,MSFT,23657745
10,134.1500,134.15,2019-06-27,0.0,134.710,MSFT2019-06-27,133.5100,134.14,1.0,MSFT,16557482
9,133.9600,133.96,2019-06-28,0.0,134.600,MSFT2019-06-28,133.1558,134.57,1.0,MSFT,30042969
8,135.6800,135.68,2019-07-01,0.0,136.700,MSFT2019-07-01,134.9700,136.63,1.0,MSFT,22654160
7,136.5800,136.58,2019-07-02,0.0,136.590,MSFT2019-07-02,135.3400,136.12,1.0,MSFT,15237843
6,137.4600,137.46,2019-07-03,0.0,137.740,MSFT2019-07-03,136.2950,136.80,1.0,MSFT,13629296
5,137.0600,137.06,2019-07-05,0.0,137.330,MSFT2019-07-05,135.7200,135.94,1.0,MSFT,18128543
4,136.9600,136.96,2019-07-08,0.0,137.080,MSFT2019-07-08,135.3701,136.40,1.0,MSFT,13757266
3,136.4600,136.46,2019-07-09,0.0,136.970,MSFT2019-07-09,135.8000,136.00,1.0,MSFT,19614848
2,137.8500,137.85,2019-07-10,0.0,138.580,MSFT2019-07-10,137.0200,137.13,1.0,MSFT,24204362
1,138.4000,138.40,2019-07-11,0.0,139.220,MSFT2019-07-11,137.8700,138.20,1.0,MSFT,22327942
0,138.9000,138.90,2019-07-12,0.0,139.130,MSFT2019-07-12,138.0099,138.85,1.0,MSFT,18884297

In [228]:
# Target value - i days into the future
i = 2
target = (df["adjusted_close"].shift(-i) - df["adjusted_close"]) / df["adjusted_close"]

In [ ]:
# from sklearn.base import BaseEstimator, ClassifierMixin

# class stockTransformer(BaseEstimator, ClassifierMixin):
#     def __init__(self):
#         pass

#     def fit(self, X, y=None):
#         return self

#     def _meaning(self, x):
#         return(True)

#     def transform(self, tmp, y=None):
#         #Vi tittar tillbaka {i} dagar
#         for j in [1,2,3,5,7,10]: #range(1, 10):
#             for c in ["adjusted_close", "high", "low", "open", "volume"]: #"close", 
#                 tmp["hist_{}_{}".format(c,j)] = (tmp[c].shift(j) - tmp[c]) / tmp[c]

#         # Date -> month / day
#         tmp["month"] = tmp["date"].apply(lambda x : x.split("-")[1])
#         tmp["day"] = tmp["date"].apply(lambda x : x.split("-")[2])

#         tmp = tmp.drop(["adjusted_close", "close", "date", "dividend_amount", "high", "id", "low", "open", "split_coefficient", "symbol", "volume"], axis=1)
#         return tmp.fillna(-1)  # TODO - ta bort NaN frÃ¥n bÃ¥de X/Y
        
#     def predict(self, X, y=None):
#         return(X)

#     def score(self, X, y=None):
#         return(sum(self.predict(X)))

In [237]:
from pandas import Timestamp
t = Timestamp("1999-02-02")
str(t).split("-")
# st = stockTransformer()
# tmp = st.transform(df)[:2]

['1999', '02', '02 00:00:00']

In [255]:
import pandas
# df.date = df.date.astype(str)
# df.info()

# df.date.map(lambda x: x.split("-"))
# df.date.astype()
tmp = df.to_json()
j = pandas.read_json(tmp)
j.date = j.date.astype(str)
j.head().date.map(lambda x: str(x).split("-"))

0       [2019, 07, 12]
1       [2019, 07, 11]
10      [2019, 06, 27]
100     [2019, 02, 19]
1000    [2015, 07, 22]
Name: date, dtype: object

In [256]:
import requests

url = "http://127.0.0.1:5002/invocations"
data = df[:2]
headers = {
    'Content-Type': 'application/json; format=pandas-split',
}

response = requests.post(url, headers=headers, data=data.to_json(orient='split'))
response.text
# data.to_json()
# data

'[-0.010185381292896664, -0.0018984001592138808]'

In [186]:
#
# Wine test
#

import pandas as pd 

wine_path = "/home/hades/program/python/jupyter/stock19/wine-quality.csv"
data = pd.read_csv(wine_path)

url = "http://127.0.0.1:5003/invocations"
data = data[:2] #.to_json()

headers = {
    'Content-Type': 'application/json; format=pandas-split',
}


# d2 = '{"columns":["alcohol", "chlorides", "citric acid", "density", "fixed acidity", "free sulfur dioxide", "pH", "residual sugar", "sulphates", "total sulfur dioxide", "volatile acidity"],"data":[[12.8, 0.029, 0.48, 0.98, 6.2, 29, 3.33, 1.2, 0.39, 75, 0.66]]}'

response = requests.post('http://127.0.0.1:5003/invocations', headers=headers, data=data.drop(columns=['quality']).to_json(orient='split'))
response.text

# print(d)
# print()
# print(str(d2))
# data.to_json()
# data.drop(columns=['quality']).to_json()

'[5.655099099229193, 5.630318463109261]'